---

  - name: "show remote environment"
    shell: env  

  - name: "copy backend binaries"
    become: true
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/udapeople
      recursive: true

  - name: "copy node modules"
    become: true
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/udapeople
      recursive: true

  - name: "stop running processes"
    become: true
    shell: |
      npm run migrations
      pm2 stop default
    ignore_errors: true

  - name: "start server"
    become: true
    command: pm2 start npm -- start
    args:
      chdir: /home/ubuntu/udapeople

    environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     ANSIBLE_HOST_KEY_CHECKING: False
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"